name: First workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "hello world1"
          echo "hello world2"
          echo "hello world3"
      - name: Print goodbye
        run: |
          echo "done - bye1"
          echo "done - bye2"
          echo "done - bye3"
